// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: movie.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetListMovieRequest) Validate() error {
	return nil
}
func (this *DataFilmList) Validate() error {
	if this.Detail != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Detail); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Detail", err)
		}
	}
	return nil
}
func (this *ResponseListFilm) Validate() error {
	for _, item := range this.ListFilm {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ListFilm", err)
			}
		}
	}
	return nil
}
func (this *GetDetailMovieRequest) Validate() error {
	return nil
}
func (this *ResponseGetDetailMovie) Validate() error {
	for _, item := range this.Rating {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Rating", err)
			}
		}
	}
	return nil
}
func (this *Ratings) Validate() error {
	return nil
}
